---
# Check and see if the GPG key already exists on the host
- name: Docker | CE | APT | Add GPG Key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"
    state: "present"
  register: add_repository_key
  ignore_errors: true

# If the GPG key doesn't exist, then add the new GPG key
- name: Docker | CE | APT | Add Docker GPG Key
  shell: curl -fsSL {{ docker_apt_key_url }} | sudo apt-key add -
  failed_when: false
  changed_when: false
  when: add_repository_key|failed

#Docker’s APT repository contains Docker 1.7.1 and higher.
- name: Docker | CE | APT | Configure Docker repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    state: present

- name: Docker | CE | APT | Enable Edge repository
  apt_repository:
    repo: "{{ docker_apt_repo_url_edge }}"
    state: present
  when: docker_channel == "edge"
  notify: Docker | CE | APT | Upgrade to Edge
